spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dec
    username: dec
    password: dec
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
server:
  port: 8087
