spring:
  datasource:
    url: jdbc:h2:mem:mybatis_labs
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:/schema.sql
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

