version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dec
      POSTGRES_USER: dec
      POSTGRES_PASSWORD: dec
    ports:
      - "5432:5432"
    volumes:
      - dec_pg_data:/var/lib/postgresql/data
volumes:
  dec_pg_data:
