services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mqlabs
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
  kafka:
    image: bitnami/kafka:3.6.1
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "PLAINTEXT"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9092"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  rocketmq-namesrv:
    image: apache/rocketmq:5.2.0
    command: ["sh","-c","/bin/mqnamesrv"]
    ports:
      - "9876:9876"
  rocketmq-broker:
    image: apache/rocketmq:5.2.0
    depends_on:
      - rocketmq-namesrv
    command: ["sh","-c","/bin/mqbroker -n rocketmq-namesrv:9876"]
    ports:
      - "10911:10911"
      - "10909:10909"
